name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Generate Docker image tag
      id: docker-tag
      run: echo "::set-output name=tag::$(date -u +'%Y.%m.%d')-$(uuidgen | cut -c 1-8)"

    - name: Docker login
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_HUB_NAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./
        push: true
        tags: |
          bskjon/debian-azuljava17-ffmpeg:latest
          bskjon/debian-azuljava17-ffmpeg:${{ github.sha }}
          bskjon/debian-azuljava17-ffmpeg:${{ steps.docker-tag.outputs.tag }}
